# Generated by Django 3.2.6 on 2021-09-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('contno', models.TextField(blank=True, db_column='contNo', null=True)),
                ('dmgloc', models.TextField(blank=True, db_column='dmgLoc', null=True)),
                ('compcode', models.TextField(blank=True, db_column='compCode', null=True)),
                ('dmgcode', models.TextField(blank=True, db_column='dmgCode', null=True)),
                ('actrpr', models.TextField(blank=True, db_column='actRpr', null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('rprqty', models.FloatField(blank=True, db_column='rprQty', null=True)),
                ('manhour', models.FloatField(blank=True, null=True)),
                ('manhourdps', models.TextField(blank=True, db_column='manhourDPS', null=True)),
                ('matidr', models.FloatField(blank=True, db_column='matIdr', null=True)),
                ('materialdps', models.TextField(blank=True, db_column='materialDPS', null=True)),
                ('respparty', models.TextField(blank=True, db_column='respParty', null=True)),
                ('eorno', models.TextField(blank=True, db_column='EORNo', null=True)),
                ('rprcreate', models.DateTimeField(blank=True, db_column='rprCreate', null=True)),
                ('approve', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'repair',
            },
        ),
    ]
