# Generated by Django 3.2.6 on 2021-09-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('contno', models.TextField(blank=True, db_column='contNo', null=True)),
                ('dmgloc', models.TextField(blank=True, db_column='dmgLoc', null=True)),
                ('dmgcode', models.TextField(blank=True, db_column='dmgCode', null=True)),
                ('compcode', models.TextField(blank=True, db_column='compCode', null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('lebar', models.FloatField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('rprqty', models.FloatField(blank=True, db_column='rprQty', null=True)),
                ('manhour', models.FloatField(blank=True, null=True)),
                ('matidr', models.FloatField(blank=True, db_column='matIdr', null=True)),
                ('actrpr', models.TextField(blank=True, db_column='actRpr', null=True)),
                ('respparty', models.TextField(blank=True, db_column='respParty', null=True)),
                ('eorno', models.TextField(blank=True, db_column='EORNo', null=True)),
                ('rprcreate', models.DateTimeField(blank=True, db_column='rprCreate', null=True)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='report_Pdf',
        ),
    ]
