# Generated by Django 3.2.6 on 2021-08-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='generate_excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=30, verbose_name='Client')),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
