# Generated by Django 3.2.6 on 2021-08-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generate_excel',
            name='end_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generate_excel',
            name='start_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
